# Generated by Django 5.2.8 on 2025-11-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='NewsletterSubscriber',
        ),
    ]
