# Generated by Django 5.2 on 2025-12-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_rename_subscriber_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
